import React,{useEffect,useRef,useState}from"react";import{createRoot}from"react-dom/client";import*as Cesium from"cesium";import"cesium/Build/Cesium/Widgets/widgets.css";import{config,earthquakes,flights,geocode}from"./data/api";import{addEarthquakes,addFlights,clear}from"./cesium/World";import{addSatelliteRows}from"./cesium/Satellites";import Timeline from"./components/Timeline";import Inspector from"./components/Inspector";import SourceStatus from"./components/SourceStatus";import"./styles.css";
const MIN=Date.parse("2026-08-16T08:00:00Z"),MAX=Date.parse("2026-08-16T14:00:00Z");
function App(){const el=useRef(),vref=useRef();const[token,setToken]=useState(""),[ready,setReady]=useState(false),[q,setQ]=useState(""),[eq,setEq]=useState(),[air,setAir]=useState(),[sat,setSat]=useState(),[events,setEvents]=useState([]),[selected,setSelected]=useState(null),[mode,setMode]=useState("replay"),[time,setTime]=useState(MIN),[play,setPlay]=useState(false),[speed,setSpeed]=useState(15),[layers,setLayers]=useState({eq:true,air:false,sat:true,replay:true}),[sources,setSources]=useState({USGS:"LOADING",OpenSky:"STANDBY",CelesTrak:"LOADING"});
useEffect(()=>{config().then(x=>setToken(x.cesiumIonToken||""));earthquakes().then(x=>{setEq(x);setSources(s=>({...s,USGS:"ONLINE"}))}).catch(()=>setSources(s=>({...s,USGS:"ERROR"})));fetch("/api/replay/demo").then(r=>r.json()).then(x=>setEvents(x.events||[]));},[]);
useEffect(()=>{if(layers.air)flights().then(x=>{setAir(x);setSources(s=>({...s,OpenSky:"ONLINE"}))}).catch(()=>setSources(s=>({...s,OpenSky:"RATE LIMITED"})))},[layers.air]);
useEffect(()=>{if(layers.sat)fetch("/api/data/satellite-positions?group=visual").then(r=>r.json()).then(x=>{setSat(x);setSources(s=>({...s,CelesTrak:"ONLINE"}))}).catch(()=>setSources(s=>({...s,CelesTrak:"ERROR"})))},[layers.sat]);
useEffect(()=>{let v;async function boot(){if(token)Cesium.Ion.defaultAccessToken=token;const terrain=token?await Cesium.CesiumTerrainProvider.fromIonAssetId(1):new Cesium.EllipsoidTerrainProvider();let base=token?await Cesium.IonImageryProvider.fromAssetId(2):undefined;v=new Cesium.Viewer(el.current,{animation:false,baseLayer:base,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,timeline:false,infoBox:false,selectionIndicator:false,terrainProvider:terrain,shouldAnimate:true});v.scene.globe.enableLighting=true;v.scene.skyAtmosphere.show=true;v.scene.fog.enabled=true;v.scene.postProcessStages.fxaa.enabled=true;v.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(44,28,16500000),duration:2});v.screenSpaceEventHandler.setInputAction(c=>{const p=v.scene.pick(c.position);const pp=p?.id?.properties;if(pp){const obj={};for(const k of pp.propertyNames)obj[k]=pp.getValue(v.clock.currentTime);setSelected(obj)}},Cesium.ScreenSpaceEventType.LEFT_CLICK);vref.current=v;setReady(true)}boot();return()=>v?.destroy()},[token]);
useEffect(()=>{if(!play||mode!=="replay")return;const id=setInterval(()=>setTime(t=>t+1000*speed>=MAX?MIN:t+1000*speed),1000);return()=>clearInterval(id)},[play,speed,mode]);
useEffect(()=>{const v=vref.current;if(!v||!ready)return;clear(v);if(mode==="live"){if(layers.eq)addEarthquakes(v,eq);if(layers.air)addFlights(v,air);if(layers.sat)addSatelliteRows(v,sat?.rows)}else if(layers.replay){for(const e of events.filter(x=>Date.parse(x.time)<=time)){v.entities.add({position:Cesium.Cartesian3.fromDegrees(e.lon,e.lat,0),point:{pixelSize:10,color:e.kind==="incident"?Cesium.Color.RED:e.kind==="airspace"?Cesium.Color.YELLOW:Cesium.Color.CYAN,outlineColor:Cesium.Color.WHITE,outlineWidth:1},properties:new Cesium.PropertyBag({type:e.kind,title:e.title,time:e.time,latitude:e.lat,longitude:e.lon})})}}},[ready,mode,layers,eq,air,sat,events,time]);
function search(){geocode(q).then(a=>{const x=a?.[0];if(x&&vref.current)vref.current.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(+x.lon,+x.lat,260000),duration:2})})}
return <div className="app"><div className="globe" ref={el}/><div className="scanline"/><header><div className="brand"><div className="mark">◎</div><div><div className="logo">WORLDVIEW</div><div className="tag">LIVE OPEN-SOURCE SPATIAL INTELLIGENCE</div></div></div><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Search the world…"/><button onClick={search}>GO</button></div><div className="live">{ready?"● LIVE":"◌ BOOTING"}</div></header><nav className="rail"><button>☰</button><button onClick={()=>vref.current?.camera.flyHome(1.5)}>⌂</button><button onClick={()=>setMode(mode==="live"?"replay":"live")}>{mode==="live"?"4D":"LIVE"}</button></nav><aside className="stack"><div className="panel"><div className="k">WORLD STATUS</div><h3>{mode==="replay"?"4D REPLAY":"LIVE MONITOR"}</h3><div className="sub">{ready?"Cesium/WebGL online":"Initializing globe"}</div></div><div className="panel"><div className="k">LAYERS</div>{[["eq","EARTHQUAKES"],["air","AIRCRAFT"],["sat","SATELLITES"],["replay","REPLAY EVENTS"]].map(([k,l])=><label key={k}><span>{l}</span><input type="checkbox" checked={layers[k]} onChange={e=>setLayers(x=>({...x,[k]:e.target.checked}))}/></label>)}</div><SourceStatus health={sources}/></aside><div className="top-right"><div className="panel"><div className="k">EVENTS</div><b>{mode==="replay"?events.filter(e=>Date.parse(e.time)<=time).length:(eq?.features?.length??0)}</b><span> ACTIVE OBJECTS</span></div></div>{selected&&<Inspector selected={selected} onClose={()=>setSelected(null)}/>}<Timeline open={true} playing={play} setPlaying={setPlay} time={time} setTime={setTime} min={MIN} max={MAX} speed={speed} setSpeed={setSpeed} mode={mode} setMode={setMode}/><div className="footer"><span>WORLDVIEW / GOD'S-EYE-STYLE OPEN SOURCE BUILD</span><span>PHASE 5 / 5</span></div></div>}
createRoot(document.getElementById("root")).render(<App/>);
